config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/brainstorage', as: 'rails_admin'
  # mount ActionCable.server => '/cable'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'menu#index'
  resources :orders, only: [:create, :new]
  resources :order_items, only: [:update, :destroy]
  resources :orders_panel, only: [:index]
  resources :menu, only: [:index, :show]
  resources :statistics, only: [:index]

  get '/...', to: 'menu#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  include AwesomeNestedSetMethods

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" },
                            default_url: "/missing.png"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_with AttachmentSizeValidator, attributes: :image, less_than: 1.megabytes

  validates :name, length: { minimum: 3 }, presence: true, uniqueness: true
  has_many :items
  acts_as_nested_set

  before_save   :name_capitalize
  after_create  :parent_count_increase
  after_destroy :parent_count_decrease
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category

  validates :name, length: { minimum: 3 }, presence: true, uniqueness: true
  validates :category_id, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  before_save :set_current_order_number

  has_many :order_items, dependent: :destroy

  scope :order_number_today, -> { where('DATE(created_at) = ?', Time.zone.now).size }

  VALID_STATES = [
    COOKING = 1,
    COOKED  = 2,
    SENDED  = 3
  ].freeze

  private

  def set_current_order_number
    return if current_number.positive?
    self.current_number = Order.order_number_today + 1
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  before_save :sum_price

  belongs_to :order, counter_cache: true

  validates :quantity, presence: true, numericality: {
    only_integer: true, greater_than_or_equal_to: 1
  }

  validates :total_price, presence: true

  validates :order_id, presence: true
  validates :item_id, presence: true

  def item
    Item.find(item_id)
  end

  private

  def sum_price
    self.total_price = quantity * Item.find(item_id).price
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  rolify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  include OrdersHelper

  before_action :set_current_order_with_total_price

  def index
    @menu = Category.roots
  end

  def show
    @menu = if Category.find(params[:id]).children.size.positive?
              Category.find(params[:id]).children
            else
              [Category.find(params[:id])]
            end
  end

  private

  def set_current_order_with_total_price
    @total_price = current_order.order_items.pluck(:total_price).map.sum.to_s
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  include OrdersHelper

  before_action :set_order

  def update
    order_item = OrderItem.find(params[:id])

    respond_to do |format|
      if order_item.update(order_item_params)
        format.json { render json: { order_item: order_item, order_total_price: @order.order_items.pluck(:total_price).sum } }
      else
        format.json { render json: order_item.errors }
      end
    end
  end

  def destroy
    order_item = OrderItem.find(params[:id])

    respond_to do |format|
      if order_item.destroy
        format.json { render json: { order_total_price: @order.order_items.pluck(:total_price).sum } }
      else
        format.json { render json: order_item.errors }
      end
    end
  end

  private

  def order_item_params
    params.require(:order).permit(:quantity)
  end

  def set_order
    current_order
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include OrdersHelper

  before_action :current_order

  def create
    order_item = @order.order_items.build(order_params)

    respond_to do |format|
      if order_item.save
        response = { order_item: order_item, order_total_price: total_price }
        format.json { render json: response }
      else
        format.json { render json: order_item.errors }
      end
    end
  end

  def new
    order_status(params[:order][:status])
    delete_order_from_cookie
    send_notify_to_kitchen
    respond_to do |format|
      if session[:order_id].nil?
        format.json { render json: { status: 'Созднан новый заказ' } }
      else
        format.json { render json: { status: 'Ошибка создания заказа' } }
      end
    end
  end

  private

  def order_params
    params.require(:order).permit(:item_id, :quantity)
          .merge(total_price: Item.find(params[:order][:item_id]).price)
  end
end

app/controllers/orders_panel_controller.rb
class OrdersPanelController < ApplicationController
  include OrdersHelper

  def index
    @orders = OrderSearcher.new(orders_params).call
  end

  private

  def orders_params
    orders_today_with_status(params[:status])
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
    @statistic = OrderSearcher.new(statistics_params).call
  end

  private

  def statistics_params
    params.permit(:item_id, :start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  private

  def delete_order_from_cookie
    session[:order_id] = nil
  end

  def orders_today_positive?
    params = {
      start_date: Time.zone.now.to_date.beginning_of_day,
      end_date: Time.zone.now.to_date.end_of_date
    }
    OrderSearcher.new(params).call.size.positive?
  end

  def orders_today_with_status(status)
    { start_date: Time.zone.now.to_date.beginning_of_day,
      end_date: Time.zone.now.to_date.end_of_day,
      status: status }
  end

  def total_price
    @order.order_items.pluck(:total_price).sum.to_s
  end

  def current_order
    @order = Order.find(session[:order_id])
  rescue ActiveRecord::RecordNotFound
    session[:order_id] = Order.create.id
    @order = Order.includes(:order_items).find(session[:order_id])
  end

  def order_status(status)
    @order.update_attributes!(status: status)
  end

  def send_notify_to_kitchen
    OrdersChannel.broadcast_to :orders, order: render_order(@order)
  end

  def render_order(order)
    OrdersPanelController.render partial: 'orders_panel/order',
                                 locals: { order: order }
  end
end

app/helpers/orders_panel_helper.rb
module OrdersPanelHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/home/index.html.slim
p Hello

app/views/menu/_order_panel.html.slim
div.row
  div.row.alert.alert-success
    h2.text-center Меню ресторана
  div.column.col-xs-3 id="sidebar"
    h2 id="order" Заказ № #{Order.order_number_today}
    h2 id="total_price" Итого: #{@total_price} рублей
    = button_tag 'Распечатать заказ и принять новый', class: 'btn btn-success', id: "print_order"
    br
    br
    - @order.order_items.each do |order_item|
        div.bordered id="order_item_#{order_item.id}_block"
          div.row
            p id="order_item_#{order_item.id}" #{order_item.item.name}
            div.row
              div.column.col-xs-6
                input type="number" class="form-control" min="1" id="order_item_#{order_item.id}_quantity" item_id="#{order_item.item_id}" value="#{order_item.quantity}"
              div.column.col-xs-2
                = button_tag 'Удалить', class: 'btn btn-warning', id: "order_item_#{order_item.id}_remove", method: :delete

app/views/menu/index.html.slim
= render "order_panel"

div.column.col-xs-9
  - @menu.each do |category|
    - if category.children.size.positive?
      div.col-sm-6.col-md-4
        .thumbnail
          = link_to (image_tag category.image.url(:medium)), menu_path(category.id)
          .caption
             = link_to category.name, menu_path(category.id)
    - else
      - category.items.each do |item|
          = item.name
          = button_tag 'Добавить в заказ', value: item.name, class: 'btn btn-success', id: "item_#{item.id}"

app/views/menu/show.html.slim
= render "order_panel"

div.column.col-xs-9
  div.row
    - if @menu.size > 1
      - @menu.each do |category|
          div.col-sm-6.col-md-4
            .thumbnail
              = link_to (image_tag category.image.url(:medium)), menu_path(category.id)
              = link_to category.name, menu_path(category.id)
    - else
      - @menu.each do |category|
        - category.items.each do |item|
            div.col-sm-6.col-md-4
              .thumbnail
                .caption
                  h3 = item.name
                  h4 = "#{item.price} р"
                  = button_tag 'Добавить в заказ', value: item.name, class: 'btn btn-success', id: "item_#{item.id}"       

app/views/orders_panel/_order.html.slim
div.column.col-xs-9
  div.col-sm-6.col-md-4
    .thumbnail
    .caption
      h3 = order.id
      h4 = order.inspect
      = button_tag 'Добавить в заказ', value: '', class: 'btn btn-success', id: ""       

app/views/orders_panel/index.html.slim
div.row
  div id='order_panel'
    div.column.col-xs-2
      h3 =link_to 'Готовится', orders_panel_index_path(status: Order::COOKING)
      h3 =link_to 'Готовые', orders_panel_index_path(status: Order::COOKED)
      h3 =link_to 'Отданные', orders_panel_index_path(status: Order::SENDED)
  div.column.col-xs-9
    div.row    
      table.table
        th Номер заказа
        th Имя
        th Количество
        th Цена за еденицу
        th Итого
        th Итого за весь заказ
        - @orders.each do |order|
            - order.order_items.each do |order_item|
                tr id="order_number_#{order.current_number}_item"
                  td = order.current_number
                  td = order_item.item.name
                  td = order_item.quantity
                  td = order_item.item.price
                  td = order_item.total_price
            tr id="order_number_#{order.current_number}_total_price"
              td button_tag
              td
              td
              td
              td
              td = order.order_items.pluck(:total_price).map.sum.to_s

app/views/statistics/index.html.slim
div.row
  div.row.alert.alert-success
    h2.text-center Статистика
dib.row
  h2 Общая статистика заказов по дням
  = column_chart Order.group_by_day_of_week(:created_at, format: "%a").count
div.row
  h2 Составить отчет
  = form_tag statistics_path, method: :get
      div.row
        = select_tag :item_id, options_from_collection_for_select(Item.all, :id, :name, params[:item_id]),  include_blank: 'Все товары', class: "btn btn-default"
        = text_field_tag 'start_date', params[:start_date] || '', data: { provide: 'datepicker', date_format: 'dd.mm.yyyy' }
        = text_field_tag 'end_date', params[:end_date] || '', data: { provide: 'datepicker', date_format: 'dd.mm.yyyy' }
        = submit_tag "Поиск", class: "btn btn-default"
  div.row
    table.table
      th Дата
      th Имя
      th Количество
      th Цена за еденицу
      th Итого
      th Итого за весь заказ
      - @statistic.each do |order|
          - order.order_items.each do |order_item|
              tr
                td = order.created_at.strftime('%d.%m.%Y')
                td = order_item.item.name
                td = order_item.quantity
                td = order_item.item.price
                td = order_item.total_price
          tr
            td
            td
            td
            td
            td
            td = order.order_items.pluck(:total_price).map.sum.to_s
          